# Config file for automatic testing at travis-ci.org

language: python
python: 2.7

env:
  - TOXENV=py27
  - TOXENV=py34
  - TOXENV=pypy

install:
  - pip install tox --use-mirrors

script: tox

after_success:
    # Report coverage results to codecov.io
    - pip install codecov
    - codecov

