# Config file for automatic testing at travis-ci.org
sudo: true

before_install:
  - sudo mkdir -p /etc/oar
  - sudo chown -R $USER /etc/oar

language: python
python: 2.7

env:
  - TOXENV=py27
  - TOXENV=py34
  - TOXENV=py33

install:
  - pip install tox

script: tox

after_success:
    # Report coverage results to codecov.io
    - pip install codecov
    - codecov
