# Config file for automatic testing at travis-ci.org
sudo: true

before_install:
  - sudo mkdir -p /etc/oar
  - sudo chown -R $USER /etc/oar

language: python
python: 2.7

env:
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34

install:
  - pip install tox coverage
  - coverage erase

script:
  - tox -v

after_success:
    - coverage combine
    # Report coverage results to codecov.io
    - pip install codecov
    - codecov
