# Config file for automatic testing at travis-ci.org
sudo: false

language: python
python: 2.7

env:
  - TOXENV=py27
  - TOXENV=py34
  - TOXENV=py33
  - TOXENV=pypy

install:
  - pip install tox

script: tox

after_success:
    # Report coverage results to codecov.io
    - pip install codecov
    - codecov
